version: "3.7"

services:
  go-multi-room-chat:
    image: "go-multi-room-chat:latest"
    container_name: "go-multi-room-chat"
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - 9000:8080
    environment:
      MODE: PRODUCTION
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      CHAT_MESSAGE_LIFETIME: 1
    restart: always
    network_mode: bridge
