version: "3.7"

services:
  golang-multi-room-chat:
    image: "golang-multi-room-chat"
    container_name: "golang-multi-room-chat"
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - MODE=PRODUCTION
      - SERVER_HOST=
      - SERVER_PORT=8080
      - CHAT_MESSAGE_LIFETIME=1
    restart: always
    network_mode: bridge
