version: "3.7"

services:
  golang-multi-room-chat:
    image: "golang-multi-room-chat"
    container_name: "golang-multi-room-chat"
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    network_mode: bridge
